create table tb_aluno (id int8 generated by default as identity, aluno varchar(255), atividade varchar(255), disciplina varchar(255), primary key (id));
create table tb_aluno (id int8 generated by default as identity, aluno varchar(255), atividade varchar(255), disciplina varchar(255), primary key (id));
