create table tb_tipo (id int8 generated by default as identity, tipo_nome varchar(255), primary key (id));
create table tb_user (id int8 generated by default as identity, email varchar(255), nome varchar(255), senha varchar(255), primary key (id));
create table tb_user_tipo (user_id int8 not null, tipo_id int8 not null, primary key (user_id, tipo_id));
alter table if exists tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
alter table if exists tb_user_tipo add constraint FKa5d01ioaqjwn2ifluvdbqf703 foreign key (tipo_id) references tb_tipo;
alter table if exists tb_user_tipo add constraint FK1e0mk8odou3mjvhm73havaw0m foreign key (user_id) references tb_user;
